services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\FeedGenerator\:
    resource: '../Classes/*'
    exclude: '../Classes/{Attributes,Configuration/FeedConfiguration,Item}'

  Brotkrueml\FeedGenerator\Configuration\FeedRegistry:
    arguments:
      - !tagged_iterator tx_feed_generator.feed

  feed_generator.configuration.module.feed_configuration:
    class: Brotkrueml\FeedGenerator\ConfigurationModule\FeedProvider
    tags:
      - name: 'lowlevel.configuration.module.provider'
        identifier: 'feed-generator/feed-provider'
