services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\FeedGenerator\:
    resource: '../Classes/*'
    exclude: '../Classes/{Attributes,Configuration/FeedConfiguration,Entity,ValueObject}'

  _instanceof:
    Brotkrueml\FeedGenerator\Renderer\RendererInterface:
      public: true

  Brotkrueml\FeedGenerator\Configuration\ExtensionRegistry:
    arguments:
      - !tagged_iterator tx_feed_generator.extension

  Brotkrueml\FeedGenerator\Configuration\FeedRegistry:
    arguments:
      - !tagged_iterator tx_feed_generator.feed

  feed_generator.configuration.module.feeds:
    class: Brotkrueml\FeedGenerator\ConfigurationModule\FeedProvider
    tags:
      - name: 'lowlevel.configuration.module.provider'
        identifier: 'feed-generator/feed-provider'

  feed_generator.configuration.module.extensions:
    class: Brotkrueml\FeedGenerator\ConfigurationModule\ExtensionProvider
    tags:
      - name: 'lowlevel.configuration.module.provider'
        identifier: 'feed-generator/extension-provider'
